"use strict";
//data type of my object.
// person object.
// persnal biodata.
let person = {
    name: "Laiba Naz",
    fatherName: "Gulfaraz Ahmed",
    nationality: "Pakistan",
    Student: true,
    Qualification: "inter",
    age: 18,
    phoneNumber: "307xxxxx28",
    email: "rajlaiba65@gmail.com",
    Gender: "Female",
    Address: "xyz baldia town ittehad town karachi",
    Sibling: "5 sister and 2 brother",
    placeofbirth: "Karachi",
    dateofbirth: "24th.12.2005",
    bloodGroup: "AB positive",
    Height: "5 feet 6 inches",
    weight: "55 kg ",
    languageKnown: "English, urdu, hindko, punjabi",
    getting: "Getting respect",
    religion: "Islam",
    cast: "Rajpoot",
    motherTongue: "Hindko",
    belong: "kpk",
    fatherOccupation: "Late",
    motherOccupation: "House Wife",
    materialStatus: "single",
    goals: "Successful life",
    // fav food.
    favouriteFood1: "Biryani",
    favouriteFood2: "Shami Kabab",
    favouriteFood3: "korma",
    favouriteFood4: "Mater rice",
    favouriteFood5: "White Karai",
    favouriteFood6: "Allu Kabab",
    // fav fast-food.
    favouritefastFood1: "Biryani",
    favouritefastFood2: "Zinger burger",
    favouritefastFood3: "zinger roll",
    favouritefastFood4: "fries",
    favouritefastFood5: "Broast",
    favouritefastFood6: "Chicken roll",
    // fav color.
    favouriteColor1: "Black",
    favouriteColor2: "yellow",
    favouriteColor3: "brown",
    favouriteColor4: "green",
    // fav Place.
    favouritePlace1: "Naran",
    favouritePlace2: "Kagan",
    favouritePlace3: "Sawat",
    favouritePlace4: "Maree",
    favouritePlace5: "Malam Jabba",
    favouritePlace6: "Gilgit",
    favouritePlace7: "Nathiya Gali",
    favouritePlace8: "Mansara",
    favouritePlace9: "Margala",
    favouritePlace10: "Chitral",
    // fav city.
    favouriteCity1: "Islamabad",
    favouriteCity2: "Lahore",
    favouriteCity3: "Karachi",
    favouriteCity4: "Multan",
    favouriteCity5: "Rawalpindi",
    favouriteCity6: "Sailkot",
    // fav Picnic Point.
    PicnicPoint1: "Sea View",
    PicnicPoint2: "Clifton",
    PicnicPoint3: "Port Grand",
    PicnicPoint4: "Fiesta",
    PicnicPoint5: "Garden",
    PicnicPoint6: "Adventure Land",
    PicnicPoint7: "Paradies",
    PicnicPoint8: "Dream World",
    PicnicPoint9: "World Water Park",
    PicnicPoint10: "PAF Musium",
    //  fav country.
    favouriteCountry1: "Maldives",
    favouriteCountry2: "Dubai",
    favouriteCountry3: "South Africa",
    favouriteCountry4: "Landon",
    favouriteCountry5: "Singapore",
    favouriteCountry6: "Turkey",
    // fav fruite.
    favouriteFruite1: "Mango",
    favouriteFruite2: "Orange",
    favouriteFruite3: "Apple",
    favouriteFruite4: "Strawberry",
    favouriteFruite5: "Banana",
    favouriteFruite6: "Grapes",
    // fav hobby.
    Hobbies1: "Outing",
    hobbies2: "Cricket",
    hobbies3: "Shopping",
};
//print person
console.log(person);
